//Author: SAM
//Transport Management System


package jframe;

/**
 *
 * @author hp
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public Receipt(String[] obj) {
        initComponents();
        receipt(obj);
    }
    
    //Method to put information into receipt
    public void receipt(String[] obj) {
        
        lbl_transportID.setText(obj[0]);
        lbl_vehicleID.setText("Vehicle ID:     " + obj[1]);
        lbl_name.setText("Customer Name:     " + obj[2]);
        lbl_loadingPoint.setText("Loading Point:     " + obj[3]);
        lbl_deliveryPoint.setText("Delivery Name:     " + obj[4]);
        lbl_km.setText("km:     " + obj[5]);
        lbl_package.setText("Package:     " + obj[6]);
        lbl_product.setText("Prouct:     " + obj[7]);
        lbl_weight.setText("Weight:     " + obj[8]);
        lbl_loadDate.setText("Load Date:     " + obj[9]);
        lbl_deliveryDate.setText("Delivery:     " + obj[10]);
        lbl_price.setText(obj[11]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_login = new rojerusan.RSMaterialButtonCircle();
        lbl_transportID = new javax.swing.JLabel();
        lbl_vehicleID = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_loadingPoint = new javax.swing.JLabel();
        lbl_deliveryPoint = new javax.swing.JLabel();
        lbl_km = new javax.swing.JLabel();
        lbl_package = new javax.swing.JLabel();
        lbl_product = new javax.swing.JLabel();
        lbl_weight = new javax.swing.JLabel();
        lbl_loadDate = new javax.swing.JLabel();
        lbl_deliveryDate = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Receipt");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 160, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(240, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 150, 3));

        btn_login.setBackground(new java.awt.Color(204, 204, 255));
        btn_login.setText("Ok");
        btn_login.setFont(new java.awt.Font("Roboto Medium", 1, 17)); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 750, 110, 80));

        lbl_transportID.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_transportID.setForeground(new java.awt.Color(204, 204, 204));
        lbl_transportID.setText("Transportation ID:");
        jPanel1.add(lbl_transportID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 390, 30));

        lbl_vehicleID.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_vehicleID.setForeground(new java.awt.Color(204, 204, 204));
        lbl_vehicleID.setText("Vehicle ID:");
        jPanel1.add(lbl_vehicleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 390, 30));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(204, 204, 204));
        lbl_name.setText("Customer Name:\n");
        jPanel1.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 390, 30));

        lbl_loadingPoint.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_loadingPoint.setForeground(new java.awt.Color(204, 204, 204));
        lbl_loadingPoint.setText("Loading Point:");
        jPanel1.add(lbl_loadingPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 390, 30));

        lbl_deliveryPoint.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_deliveryPoint.setForeground(new java.awt.Color(204, 204, 204));
        lbl_deliveryPoint.setText("Delivery Point:");
        jPanel1.add(lbl_deliveryPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 390, 30));

        lbl_km.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_km.setForeground(new java.awt.Color(204, 204, 204));
        lbl_km.setText("Km:");
        jPanel1.add(lbl_km, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 390, 30));

        lbl_package.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_package.setForeground(new java.awt.Color(204, 204, 204));
        lbl_package.setText("Package:");
        jPanel1.add(lbl_package, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 390, 30));

        lbl_product.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_product.setForeground(new java.awt.Color(204, 204, 204));
        lbl_product.setText("Product:");
        jPanel1.add(lbl_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 390, 30));

        lbl_weight.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_weight.setForeground(new java.awt.Color(204, 204, 204));
        lbl_weight.setText("Weight:");
        jPanel1.add(lbl_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 390, 30));

        lbl_loadDate.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_loadDate.setForeground(new java.awt.Color(204, 204, 204));
        lbl_loadDate.setText("Load Date:");
        jPanel1.add(lbl_loadDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 390, 30));

        lbl_deliveryDate.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_deliveryDate.setForeground(new java.awt.Color(204, 204, 204));
        lbl_deliveryDate.setText("Delivery Date:");
        jPanel1.add(lbl_deliveryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 390, 30));

        lbl_price.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_price.setForeground(new java.awt.Color(204, 204, 204));
        lbl_price.setText("Price:");
        jPanel1.add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 390, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 870));

        setSize(new java.awt.Dimension(781, 899));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btn_login;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_deliveryDate;
    private javax.swing.JLabel lbl_deliveryPoint;
    private javax.swing.JLabel lbl_km;
    private javax.swing.JLabel lbl_loadDate;
    private javax.swing.JLabel lbl_loadingPoint;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_package;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_product;
    private javax.swing.JLabel lbl_transportID;
    private javax.swing.JLabel lbl_vehicleID;
    private javax.swing.JLabel lbl_weight;
    // End of variables declaration//GEN-END:variables
}
